export const games = [
    [
        ["West Ham", "Newcastle"],
        ["Liverpool", "Leeds"],
        ["Crystal Palace", "Southampton"],
        ["Fulham", "Arsenal"],
        ["Tottenham Hotspur", "Everton"],
        ["West Bromwich", "Leicester"],
        ["Brighton ", "Chelsea"],
        ["Sheffield ", "Wolverhampton"],
        ["Manchester City", "Burnley"],
        ["Manchester United", "Aston Villa"]
    ],
    [
        ["Liverpool", "Newcastle"],
        ["Southampton", "Arsenal"],
        ["Tottenham Hotspur", "Leeds"],
        ["Sheffield", "Everton"],
        ["West Ham", "Aston Villa"],
        ["Manchester United", "Wolverhampton"],
        ["West Bromwich", "Fulham"],
        ["Manchester City", "Crystal Palace"],
        ["Burnley", "Leicester"],
        ["Brighton", "Chelsea"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["West Ham", "Newcastle"],
        ["Liverpool", "Leeds"],
        ["Crystal Palace", "Southampton"],
        ["Fulham", "Arsenal"],
        ["Tottenham Hotspur", "Everton"],
        ["West Bromwich", "Leicester"],
        ["Brighton ", "Chelsea"],
        ["Sheffield ", "Wolverhampton"],
        ["Manchester City", "Burnley"],
        ["Manchester United", "Aston Villa"]
    ],
    [
        ["Liverpool", "Newcastle"],
        ["Southampton", "Arsenal"],
        ["Tottenham Hotspur", "Leeds"],
        ["Sheffield", "Everton"],
        ["West Ham", "Aston Villa"],
        ["Manchester United", "Wolverhampton"],
        ["West Bromwich", "Fulham"],
        ["Manchester City", "Crystal Palace"],
        ["Burnley", "Leicester"],
        ["Brighton", "Chelsea"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["West Ham", "Newcastle"],
        ["Liverpool", "Leeds"],
        ["Crystal Palace", "Southampton"],
        ["Fulham", "Arsenal"],
        ["Tottenham Hotspur", "Everton"],
        ["West Bromwich", "Leicester"],
        ["Brighton ", "Chelsea"],
        ["Sheffield ", "Wolverhampton"],
        ["Manchester City", "Burnley"],
        ["Manchester United", "Aston Villa"]
    ],
    [
        ["Liverpool", "Newcastle"],
        ["Southampton", "Arsenal"],
        ["Tottenham Hotspur", "Leeds"],
        ["Sheffield", "Everton"],
        ["West Ham", "Aston Villa"],
        ["Manchester United", "Wolverhampton"],
        ["West Bromwich", "Fulham"],
        ["Manchester City", "Crystal Palace"],
        ["Burnley", "Leicester"],
        ["Brighton", "Chelsea"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["West Ham", "Newcastle"],
        ["Liverpool", "Leeds"],
        ["Crystal Palace", "Southampton"],
        ["Fulham", "Arsenal"],
        ["Tottenham Hotspur", "Everton"],
        ["West Bromwich", "Leicester"],
        ["Brighton ", "Chelsea"],
        ["Sheffield ", "Wolverhampton"],
        ["Manchester City", "Burnley"],
        ["Manchester United", "Aston Villa"]
    ],
    [
        ["Liverpool", "Newcastle"],
        ["Southampton", "Arsenal"],
        ["Tottenham Hotspur", "Leeds"],
        ["Sheffield", "Everton"],
        ["West Ham", "Aston Villa"],
        ["Manchester United", "Wolverhampton"],
        ["West Bromwich", "Fulham"],
        ["Manchester City", "Crystal Palace"],
        ["Burnley", "Leicester"],
        ["Brighton", "Chelsea"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["West Ham", "Newcastle"],
        ["Liverpool", "Leeds"],
        ["Crystal Palace", "Southampton"],
        ["Fulham", "Arsenal"],
        ["Tottenham Hotspur", "Everton"],
        ["West Bromwich", "Leicester"],
        ["Brighton ", "Chelsea"],
        ["Sheffield ", "Wolverhampton"],
        ["Manchester City", "Burnley"],
        ["Manchester United", "Aston Villa"]
    ],
    [
        ["Liverpool", "Newcastle"],
        ["Southampton", "Arsenal"],
        ["Tottenham Hotspur", "Leeds"],
        ["Sheffield", "Everton"],
        ["West Ham", "Aston Villa"],
        ["Manchester United", "Wolverhampton"],
        ["West Bromwich", "Fulham"],
        ["Manchester City", "Crystal Palace"],
        ["Burnley", "Leicester"],
        ["Brighton", "Chelsea"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["West Ham", "Newcastle"],
        ["Liverpool", "Leeds"],
        ["Crystal Palace", "Southampton"],
        ["Fulham", "Arsenal"],
        ["Tottenham Hotspur", "Everton"],
        ["West Bromwich", "Leicester"],
        ["Brighton ", "Chelsea"],
        ["Sheffield ", "Wolverhampton"],
        ["Manchester City", "Burnley"],
        ["Manchester United", "Aston Villa"]
    ],
    [
        ["Liverpool", "Newcastle"],
        ["Southampton", "Arsenal"],
        ["Tottenham Hotspur", "Leeds"],
        ["Sheffield", "Everton"],
        ["West Ham", "Aston Villa"],
        ["Manchester United", "Wolverhampton"],
        ["West Bromwich", "Fulham"],
        ["Manchester City", "Crystal Palace"],
        ["Burnley", "Leicester"],
        ["Brighton", "Chelsea"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["West Ham", "Newcastle"],
        ["Liverpool", "Leeds"],
        ["Crystal Palace", "Southampton"],
        ["Fulham", "Arsenal"],
        ["Tottenham Hotspur", "Everton"],
        ["West Bromwich", "Leicester"],
        ["Brighton ", "Chelsea"],
        ["Sheffield ", "Wolverhampton"],
        ["Manchester City", "Burnley"],
        ["Manchester United", "Aston Villa"]
    ],
    [
        ["Liverpool", "Newcastle"],
        ["Southampton", "Arsenal"],
        ["Tottenham Hotspur", "Leeds"],
        ["Sheffield", "Everton"],
        ["West Ham", "Aston Villa"],
        ["Manchester United", "Wolverhampton"],
        ["West Bromwich", "Fulham"],
        ["Manchester City", "Crystal Palace"],
        ["Burnley", "Leicester"],
        ["Brighton", "Chelsea"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ],
    [
        ["Chelsea", "Arsenal"],
        ["Fulham", "Sheffield"],
        ["Wolverhampton", "Manchester City"],
        ["Brighton", "Tottenham Hotspur"],
        ["West Bromwich", "Liverpool"],
        ["Aston Villa", "Newcastle"],
        ["Burnley", "Southampton"],
        ["Leeds", "Crystal Palace"],
        ["Everton", "Leicester"],
        ["Manchester United", "West Ham"]
    ],
    [
        ["Leeds", "West Ham"],
        ["Sheffield", "Liverpool"],
        ["Southampton", "West Bromwich"],
        ["Brighton", "Fulham"],
        ["Everton", "Burnley"],
        ["Arsenal", "Leicester"],
        ["Newcastle", "Manchester United"],
        ["Chelsea", "Aston Villa"],
        ["Manchester City", "Tottenham Hotspur"],
        ["Crystal Palace", "Wolverhampton"]
    ],
    [
        ["Chelsea", "Newcastle"],
        ["Arsenal", "Aston Villa"],
        ["Everton", "Leeds"],
        ["Liverpool", "Sheffield"],
        ["Manchester City", "Wolverhampton"],
        ["Fulham", "Southampton"],
        ["Crystal Palace", "Manchester United"],
        ["West Ham", "Brighton"],
        ["West Bromwich", "Burnley"],
        ["Tottenham Hotspur", "Leicester"]
    ]
    
];